# Generated by Django 4.2.13 on 2024-06-13 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
