# Generated by Django 4.2.13 on 2024-07-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0004_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
